### ISSUE TITLE
Will probably not work on advanced usecases

### ISSUE THREAD

**Issue by slorber** [AvraamMavridis/redux-perf-middleware#1]
Hi,

When an action is dispatched and connect's HOC are triggered, they call setState on it. You have no guarantee that the execution of the React rendering will be synchronous to your action dispatching. It may work in your simple example but will not in more advanced ones unless react-redux's connect permits to know when all underlying components have finished to render (ie listener to this.setState's callback).

See also https://github.com/rackt/react-redux/issues/269#issuecomment-176872934

**Comment by AvraamMavridis** [comment]
@slorber Thx, I will have a look at it. Probably you are right, if your state contains DOM related info and the rendering hasnt finish the middleware will not measure correct. But, just out of curiosity, why to hold   inside your state the actual DOM info and not a description of it that React could use to build the DOM again if needed?

**Comment by slorber** [comment]
Uhhh? Where did I say that I hold DOM info inside the state? I have a perfectly reasonable usage of Redux that do not do such a thing.

When you use `connect` of Redux it builds a React component that calls `this.setState` when your selectors data changes. `setState` takes a callback so that we can know when rendering has ended (check React doc). `connect` does not use this callback (yet) so you can't know fore sure when the React rendering has ended, even if it works fine in your simple usecases.

**Comment by AvraamMavridis** [comment]
@slorber I see the issue, but I dont see how it can be fixed in the context of this middleware if redux is not using the `setState`'s callback. If you have a proposal, I am glad to hear or accept any PR.

**Comment by slorber** [comment]
@AvraamMavridis I don't expect you to do anything, it must be solved by connect first that's why I pointed to an existing react-redux issue

**Comment by AvraamMavridis** [comment]
cool.
