### ISSUE TITLE
Cant find variable performance

### ISSUE THREAD

**Issue by phoenixbox** [AvraamMavridis/redux-perf-middleware#4]
The `performance` var on `index.js:16` throws a `Cant find variable` error.

Wondering where this performance var is being referenced from? I can't find an import declaration for it and dont see it in the rest of the source code

🚀

**Comment by AvraamMavridis** [comment]
@phoenixbox which browser are you using? `performance` is part of the `window` object.

**Comment by AvraamMavridis** [comment]
I checked Firefox/Chrome and I can see the `performance`.
I will add a warning. See https://github.com/AvraamMavridis/redux-perf-middleware/issues/5

**Comment by abritinthebay** [comment]
You should probably note that this is a browser-only middleware. It will not work on Node due to this.

HOWEVER - if you want you could optionally polyfill this with the `performance-now` module. That would make this _very_ valuable for server side performance testing as well.

**Comment by AvraamMavridis** [comment]
@abritinthebay right. I will do that. Thx.
